### ISSUE TITLE
Should not have to download the font

### ISSUE THREAD

**Issue by IndieKA** [kingcodefish/star-wars-the-final-frontier#11]
Hi kcf,
I don't think players should go thru the chances to download a font. People are lazy in life.
Maybe @Eytukan should design a font for the game and we can use it.
Example:
`var myFont = function(txt, x, y){`
We could have a font defined and instead of `text` we can use `myFont`.
Just a suggestion.

**Comment by kingcodefish** [comment]
@IndieKA Did you not read the font.js file. It's supposed to be empty, and it has a comment explaining that. @Eytukan may be able to make the font, but I would have to implement it through RegEx. But for the time being, I'm making the font.

**Comment by kingcodefish** [comment]
Also, be sure to read the Style Guide file, that way you know what to make your code look like. I've updated it recently.

**Comment by kingcodefish** [comment]
BTW, I came across too abrupt in that response. Let me clarify. We are currently using Star Jedi Rounded, but that's as a placeholder. I'm in the process of making a font system so we can design the letters easily and call it as you were saying. @Eytukan could help design it if he's up to the task, which is why I assigned him to this issue. Thank you for the message, but quickly scan through our other md files and stuff to make sure you're up to speed on how we're thinking about designing things. I hope I didn't offend you that first time around.

**Comment by IndieKA** [comment]
See, this is what I mean by people are too serious and strange on KA. Not to be offenseful but people need to chill. I don't take jokes seriously lel

**Comment by kingcodefish** [comment]
I don't either, but we're that way so that other users don't see a comment that they can take seriously. New users may take them that way, when---for example---a comment says that their program doesn't deserve votes. Because they are trying hard enough on their own. We act as moderators to other comments so that the rest of the community doesn't take them seriously. Just my take on it.

The reason why I reposted is because me previous comment acted like you did something wrong. I don't want hidden meanings to take the comment the wrong way.

**Comment by IndieKA** [comment]
alright tenks.

**Comment by ghost** [comment]
I can do the font

**Comment by ghost** [comment]
I have the font downloaded and can just trace the letters

**Comment by kingcodefish** [comment]
Good to know, should I close this issue?

**Comment by ghost** [comment]
too late
